package ru.otus.otuskotlin.vd.rentalproperty.be.common.models.person

enum class PrivilegeEnum {
  USER_CREATE,
  USER_READ,
  USER_DELETE,
  USER_UPDATE,

  ROLE_CREATE,
  ROLE_READ,
  ROLE_DELETE,
  ROLE_UPDATE,

  NOTIFICATION_CREATE,
  NOTIFICATION_READ,
  NOTIFICATION_DELETE,
  NOTIFICATION_UPDATE,

  CONTENT_CREATE,
  CONTENT_READ,
  CONTENT_DELETE,
  CONTENT_UPDATE,
}