openapi: 3.0.3
info:
  title: Rental property
  description: 'Аренда недвижимости'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
tags:
  - name: realty
    description: Работа с недвижимостью
  - name: advert
    description: Работа с объявлениями

paths:
  /adverts:
    get:
      tags:
        - advert
      summary: Получить список объявлений
      responses:
        200:
          description: Успех
          content: { }

components:
  schemas:

    BaseMessage:
      type: object
      title: Базовая структура сообщения
      properties:
        type:
          type: string
          title: Тип запроса
          description: 'Идентификатор типа запроса. Используется в качестве дескриминатора при десериализации.
            Наиболее востребован при пересылке через Websocket и другие транспорты без явного выделения канала.'
      discriminator:
        propertyName: type

    RequestBase:
      type: object
      properties:
        requestId:
          type: string
          title: Идентификатор запроса
          description: Уникальный идентификатор запроса для мониторинга прохождения запроса по бэкенд-инфраструктуре
        onResponse:
          type: string
          title: Сформирован на response.id
          description: Идентификатор ответа, на который сформирован текущий запрос

    ResponseBase:
      type: object
      properties:
        responseId:
          type: string
          title: Идентификатор запроса
          description: Уникальный идентификатор запроса для мониторинга прохождения запроса по бэкенд-инфраструктуре
        onRequest:
          type: string
          title: Сформирован на request.id
          description: Идентификатор запроса, на который сформирован текущий ответ

    Item:
      allOf:
        - $ref: '#/components/schemas/ItemUpdate'
        - type: object
          title: Разрешения на единицу информации
          description: Базовая структура для основных сущностей
          properties:
            permissions:
              type: array
              uniqueItems: true
              items:
                $ref: '#/components/schemas/ItemPermission'

    ItemCreate:
      type: object
      title: Создание объекта
      description: Базовая структура для запроса создания
      properties:
        description:
          type: string
          title: Описание
          example: Описание...

    ItemUpdate:
      allOf:
        - $ref: '#/components/schemas/ItemCreate'
        - type: object
          description: Базовая структура для создания единицы информации
          properties:
            id:
              type: string
              title: Идентификатор
              example: '12343-34534-67867'

    ItemPermission:
      type: string
      enum:
        - read
        - update
        - delete

    ItemFilter:
      type: object
      title: Фильтр для поиска
      properties:
        text:
          type: string
          title: Строковое представление фильтра
