package ru.otus.otuskotlin.vd.rentalproperty.be.common.models

enum class StubCase {
  NONE,

  HOUSE_FILTER_SUCCESS,
  HOUSE_CREATE_SUCCESS,
  HOUSE_READ_SUCCESS,
  HOUSE_UPDATE_SUCCESS,
  HOUSE_DELETE_SUCCESS,
  HOUSE_OFFERS_SUCCESS,

  ADVERT_FILTER_SUCCESS,
  ADVERT_CREATE_SUCCESS,
  ADVERT_READ_SUCCESS,
  ADVERT_UPDATE_SUCCESS,
  ADVERT_DELETE_SUCCESS,
  ADVERT_OFFERS_SUCCESS,
}